# Generated by Django 3.0.2 on 2020-02-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('dni', models.IntegerField()),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=15)),
                ('distrito', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='img/clientes')),
                ('fecharegistro', models.DateTimeField()),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('raza', models.CharField(max_length=50)),
                ('años', models.IntegerField()),
                ('alergia', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='img/mascota')),
                ('fecharegistro', models.DateTimeField()),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paseador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('dni', models.IntegerField()),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=15)),
                ('experiencia', models.CharField(max_length=15)),
                ('edad', models.CharField(max_length=15)),
                ('distrito', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='img/paseador')),
                ('fecharegistro', models.DateTimeField()),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
